name: Deploy React Frontend to Azure

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: consistly-frontend-app
  AZURE_WEBAPP_PACKAGE_PATH: "./frontend/build"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package.json

      - name: Clean and install dependencies
        working-directory: ./frontend
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --legacy-peer-deps --force
          npm install ajv@^8.0.0 --legacy-peer-deps
          chmod +x node_modules/.bin/*

      - name: Build React app
        working-directory: ./frontend
        run: |
          npm run build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy using Azure CLI (fallback)
        if: failure()
        run: |
          cd frontend/build
          zip -r ../../frontend-build.zip .
          cd ../..
          az webapp deployment source config-zip --resource-group consistly-rg --name ${{ env.AZURE_WEBAPP_NAME }} --src frontend-build.zip
