name: Deploy FastAPI Backend to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: consistly-backend-app
  AZURE_WEBAPP_PACKAGE_PATH: "."

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn

      - name: Create startup command file
        run: |
          echo "gunicorn app.main:app --bind 0.0.0.0:8000 --workers 2" > startup.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_BACKEND_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Configure startup command
        run: |
          az webapp config set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group consistly-rg --startup-file "gunicorn app.main:app --bind 0.0.0.0:8000 --workers 2"
